#!/usr/bin/env python3
"""Regenerate machine and reader catalogs from every project.yaml."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from build_subtitle_packages import package_name

TYPE_LABELS = {"tv": "TV", "movie": "电影", "ova": "OVA", "ona": "ONA", "special": "特别篇"}


def scalar(text: str, name: str, indent: int = 0) -> str | None:
    match = re.search(rf"(?m)^{' ' * indent}{re.escape(name)}:\s*(.*?)\s*$", text)
    if not match:
        return None
    value = match.group(1).strip()
    if value == "null":
        return None
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        value = value[1:-1]
    return value


def section(text: str, name: str, indent: int = 0) -> str:
    lines = text.splitlines()
    prefix = " " * indent + name + ":"
    start = next((index for index, line in enumerate(lines) if line == prefix), None)
    if start is None:
        return ""
    result = []
    for line in lines[start + 1 :]:
        if line.strip() and len(line) - len(line.lstrip(" ")) <= indent:
            break
        result.append(line)
    return "\n".join(result)


def catalog_works(repository: Path) -> list[dict[str, object]]:
    works = []
    for metadata_path in repository.glob("works/**/project.yaml"):
        text = metadata_path.read_text(encoding="utf-8-sig")
        identity = section(text, "identity")
        titles = section(identity, "titles", 2)
        languages = section(section(text, "languages"), "release", 2)
        project_path = metadata_path.parent.relative_to(repository).as_posix()
        review_file = metadata_path.parent / "review.md"
        review = review_file.read_text(encoding="utf-8-sig") if review_file.is_file() else ""
        current = metadata_path.parent / "subtitles" / "current"
        version_file = current / "VERSION"
        version = version_file.read_text(encoding="utf-8").strip() if version_file.is_file() else None
        subject_id = scalar(identity, "id", 2)
        title = scalar(titles, "zh-Hans", 4)
        package = (
            repository / "packages" / package_name(metadata_path.parent, version)
            if version and subject_id and title
            else None
        )
        item = {
            "id": scalar(text, "id"), "project_path": project_path,
            "title": title, "type": scalar(text, "type"), "status": scalar(review, "overall_status") or "untracked",
            "episode_count": int(scalar(text, "episode_count") or 0), "primary": scalar(languages, "primary", 4),
            "secondary": scalar(languages, "secondary", 4), "version": version,
            "review_path": f"{project_path}/review.md", "release_path": f"{project_path}/subtitles/current" if version else None,
            "package_path": package.relative_to(repository).as_posix() if package and package.is_file() else None,
        }
        if not item["id"] or not item["title"] or item["type"] not in TYPE_LABELS:
            raise ValueError(f"invalid project metadata: {metadata_path}")
        works.append(item)
    return sorted(works, key=lambda item: int(str(item["id"])[2:]))


def render_yaml(works: list[dict[str, object]]) -> str:
    lines = ["# Generated by the package-subtitles GitHub Action; project.yaml remains authoritative.", "schema_version: 4", "", "works:"]
    for item in works:
        lines.extend([
            f"  - id: {item['id']}", f"    title: {json.dumps(item['title'], ensure_ascii=False)}",
            f"    type: {item['type']}", f"    episode_count: {item['episode_count']}",
            f"    languages: {json.dumps([value for value in (item['primary'], item['secondary']) if value], ensure_ascii=False)}",
            f"    status: {item['status']}", f"    version: {json.dumps(item['version'], ensure_ascii=False) if item['version'] else 'null'}",
            f"    project_path: {item['project_path']}", f"    review_path: {item['review_path']}",
            f"    release_path: {item['release_path'] or 'null'}", f"    package_path: {json.dumps(item['package_path'], ensure_ascii=False) if item['package_path'] else 'null'}",
        ])
    return "\n".join(lines) + "\n"


def render_markdown(works: list[dict[str, object]]) -> str:
    lines = [
        "# 字幕目录", "", "<!-- Generated by the package-subtitles GitHub Action; edit project.yaml instead. -->", "",
        "| ID | 作品 | 类型 | 集数 | 语言 / 格式 | 状态 / 版本 | 工程入口 |", "| --- | --- | --- | ---: | --- | --- | --- |",
    ]
    for item in works:
        languages = str(item["primary"])
        if item["secondary"]:
            languages += f" + {item['secondary']}"
        title_target = item["release_path"] or item["review_path"]
        version = item["version"] or "未发布"
        package_link = f"[压缩包]({item['package_path']})" if item["package_path"] else "—"
        lines.append(f"| {item['id']} | [{item['title']}]({title_target}) | {TYPE_LABELS[str(item['type'])]} | "
                     f"{item['episode_count']} | `{languages}` / ASS | `{item['status']}` / `{version}` | "
                     f"[元数据]({item['project_path']}/project.yaml) · [当前报告]({item['review_path']}) · {package_link} |")
    return "\n".join(lines) + "\n"


def indexed_package_paths(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    indexed: dict[str, str] = {}
    current_id: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        id_match = re.fullmatch(r"  - id:\s*(SH\d+)", line)
        if id_match:
            current_id = id_match.group(1)
            continue
        package_match = re.fullmatch(r"    package_path:\s*(.+)", line)
        if not package_match or current_id is None:
            continue
        value = package_match.group(1)
        if value != "null":
            indexed[current_id] = json.loads(value)
    return indexed


def package_link_mismatches(repository: Path, works: list[dict[str, object]]) -> list[str]:
    expected = {
        str(item["id"]): str(item["package_path"])
        for item in works
        if item["package_path"]
    }
    indexed = indexed_package_paths(repository / "catalog.yaml")
    ids = sorted(set(expected) | set(indexed), key=lambda value: int(value[2:]))
    return [
        f"{work_id}: indexed={indexed.get(work_id)!r}, expected={expected.get(work_id)!r}"
        for work_id in ids
        if indexed.get(work_id) != expected.get(work_id)
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--check-package-links", action="store_true")
    args = parser.parse_args()
    if args.check and args.check_package_links:
        parser.error("--check and --check-package-links are mutually exclusive")
    repository = args.repository_root.resolve()
    works = catalog_works(repository)
    if args.check_package_links:
        mismatches = package_link_mismatches(repository, works)
        if mismatches:
            print("stale package links: " + "; ".join(mismatches), file=sys.stderr)
            return 1
        print("package links valid")
        return 0
    outputs = {repository / "catalog.yaml": render_yaml(works), repository / "CATALOG.md": render_markdown(works)}
    if args.check:
        stale = [str(path) for path, expected in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != expected]
        if stale:
            print("stale derived catalog: " + ", ".join(stale), file=sys.stderr)
            return 1
        print(f"catalog valid ({len(works)} projects)")
        return 0
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    print(f"updated catalog.yaml and CATALOG.md ({len(works)} projects)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
