#!/usr/bin/env python3
"""Regenerate machine and reader catalogs from every project.yaml."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import quote

from build_subtitle_packages import package_name

TYPE_LABELS = {"tv": "TV", "movie": "电影", "ova": "OVA", "ona": "ONA", "special": "特别篇"}
REPOSITORY_SLUG = re.compile(r"[0-9A-Za-z_.-]+/[0-9A-Za-z_.-]+\Z")


def direct_download_url(repository_slug: str, package_path: str) -> str:
    if not REPOSITORY_SLUG.fullmatch(repository_slug):
        raise ValueError(f"invalid GitHub repository slug: {repository_slug!r}")
    return (
        f"https://raw.githubusercontent.com/{repository_slug}/main/"
        f"{quote(package_path, safe='/')}"
    )


def cdn_download_url(repository_slug: str, package_path: str) -> str:
    if not REPOSITORY_SLUG.fullmatch(repository_slug):
        raise ValueError(f"invalid GitHub repository slug: {repository_slug!r}")
    return f"https://cdn.jsdelivr.net/gh/{repository_slug}@main/{quote(package_path, safe='/')}"


def scalar(text: str, name: str, indent: int = 0) -> str | None:
    match = re.search(rf"(?m)^{' ' * indent}{re.escape(name)}:\s*(.*?)\s*$", text)
    if not match:
        return None
    value = match.group(1).strip()
    if value == "null":
        return None
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        value = value[1:-1]
    return value


def section(text: str, name: str, indent: int = 0) -> str:
    lines = text.splitlines()
    prefix = " " * indent + name + ":"
    start = next((index for index, line in enumerate(lines) if line == prefix), None)
    if start is None:
        return ""
    result = []
    for line in lines[start + 1 :]:
        if line.strip() and len(line) - len(line.lstrip(" ")) <= indent:
            break
        result.append(line)
    return "\n".join(result)


def catalog_works(repository: Path, repository_slug: str) -> list[dict[str, object]]:
    works = []
    for metadata_path in repository.glob("works/**/project.yaml"):
        text = metadata_path.read_text(encoding="utf-8-sig")
        identity = section(text, "identity")
        titles = section(identity, "titles", 2)
        schema = scalar(text, "schema_version")
        project_path = metadata_path.parent.relative_to(repository).as_posix()
        review_file = metadata_path.parent / "review.md"
        review = review_file.read_text(encoding="utf-8-sig") if review_file.is_file() else ""
        current = metadata_path.parent / "subtitles" / "current"
        version_file = current / "VERSION"
        version = version_file.read_text(encoding="utf-8").strip() if version_file.is_file() else None
        release_header = ""
        release_files = sorted(current.glob("*.ass")) if current.is_dir() else []
        if release_files:
            release_header = release_files[0].read_text(encoding="utf-8-sig")
        if schema == "9":
            languages = section(text, "release_languages")
            primary = scalar(languages, "primary", 2)
            secondary = scalar(languages, "secondary", 2)
        else:
            primary = scalar(release_header, "; Subtitle-Hub-Primary-Language")
            secondary = scalar(release_header, "; Subtitle-Hub-Secondary-Language")
        subject_id = scalar(identity, "id", 2)
        title = scalar(titles, "zh-Hans", 4)
        package = (
            repository / "packages" / package_name(metadata_path.parent, version)
            if version and subject_id and title
            else None
        )
        package_path = package.relative_to(repository).as_posix() if package and package.is_file() else None
        item = {
            "id": scalar(text, "id"), "project_path": project_path,
            "title": title, "type": scalar(text, "type"),
            "status": (scalar(review, "status") or "untracked") if schema == "9" else ("released" if version else "upgrade-required"),
            "episode_count": int(scalar(text, "episode_count") or 0), "primary": primary,
            "secondary": secondary, "version": version,
            "review_path": f"{project_path}/review.md", "release_path": f"{project_path}/subtitles/current" if version else None,
            "package_path": package_path,
            "package_download_url": direct_download_url(repository_slug, package_path) if package_path else None,
            "package_cdn_url": cdn_download_url(repository_slug, package_path) if package_path else None,
        }
        if not item["id"] or not item["title"] or item["type"] not in TYPE_LABELS:
            raise ValueError(f"invalid project metadata: {metadata_path}")
        works.append(item)
    return sorted(works, key=lambda item: int(str(item["id"])[2:]))


def render_yaml(works: list[dict[str, object]]) -> str:
    lines = ["# Generated by the package-subtitles GitHub Action; project.yaml remains authoritative.", "schema_version: 6", "", "works:"]
    for item in works:
        lines.extend([
            f"  - id: {item['id']}", f"    title: {json.dumps(item['title'], ensure_ascii=False)}",
            f"    type: {item['type']}", f"    episode_count: {item['episode_count']}",
            f"    languages: {json.dumps([value for value in (item['primary'], item['secondary']) if value], ensure_ascii=False)}",
            f"    status: {item['status']}", f"    version: {json.dumps(item['version'], ensure_ascii=False) if item['version'] else 'null'}",
            f"    project_path: {item['project_path']}", f"    review_path: {item['review_path']}",
            f"    release_path: {item['release_path'] or 'null'}", f"    package_path: {json.dumps(item['package_path'], ensure_ascii=False) if item['package_path'] else 'null'}",
            f"    package_download_url: {json.dumps(item['package_download_url'], ensure_ascii=False) if item['package_download_url'] else 'null'}",
            f"    package_cdn_url: {json.dumps(item['package_cdn_url'], ensure_ascii=False) if item['package_cdn_url'] else 'null'}",
        ])
    return "\n".join(lines) + "\n"


def render_markdown(works: list[dict[str, object]]) -> str:
    lines = [
        "# 字幕目录", "", "<!-- Generated by the package-subtitles GitHub Action; edit project.yaml instead. -->", "",
        "| ID | 作品 | 类型 | 集数 | 语言 / 格式 | 状态 / 版本 | 项目资料 | 字幕成品 |", "| --- | --- | --- | ---: | --- | --- | --- | --- |",
    ]
    for item in works:
        languages = str(item["primary"])
        if item["secondary"]:
            languages += f" + {item['secondary']}"
        title_target = item["release_path"] or item["review_path"]
        version = item["version"] or "未发布"
        package_links = (
            f"[原始下载]({item['package_download_url']}) · [CDN 加速]({item['package_cdn_url']})"
            if item["package_download_url"] else "—"
        )
        lines.append(f"| {item['id']} | [{item['title']}]({title_target}) | {TYPE_LABELS[str(item['type'])]} | "
                     f"{item['episode_count']} | `{languages}` / ASS | `{item['status']}` / `{version}` | "
                     f"[元数据]({item['project_path']}/project.yaml) · [当前报告]({item['review_path']}) | {package_links} |")
    return "\n".join(lines) + "\n"


def indexed_package_links(path: Path) -> dict[str, tuple[str | None, str | None, str | None]]:
    if not path.is_file():
        return {}
    indexed: dict[str, dict[str, str | None]] = {}
    current_id: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        id_match = re.fullmatch(r"  - id:\s*(SH\d+)", line)
        if id_match:
            current_id = id_match.group(1)
            indexed[current_id] = {"path": None, "url": None, "cdn": None}
            continue
        package_match = re.fullmatch(r"    package_(path|download_url|cdn_url):\s*(.+)", line)
        if not package_match or current_id is None:
            continue
        field, value = package_match.groups()
        if value != "null":
            key = {"path": "path", "download_url": "url", "cdn_url": "cdn"}[field]
            indexed[current_id][key] = json.loads(value)
    return {
        work_id: (values["path"], values["url"], values["cdn"])
        for work_id, values in indexed.items()
        if any(value is not None for value in values.values())
    }


def package_link_mismatches(repository: Path, works: list[dict[str, object]]) -> list[str]:
    expected: dict[str, tuple[str | None, str | None, str | None]] = {
        str(item["id"]): (
            str(item["package_path"]), str(item["package_download_url"]), str(item["package_cdn_url"])
        )
        for item in works
        if item["package_path"]
    }
    indexed = indexed_package_links(repository / "catalog.yaml")
    ids = sorted(set(expected) | set(indexed), key=lambda value: int(value[2:]))
    return [
        f"{work_id}: indexed={indexed.get(work_id)!r}, expected={expected.get(work_id)!r}"
        for work_id in ids
        if indexed.get(work_id) != expected.get(work_id)
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--repository-slug", default=os.getenv("GITHUB_REPOSITORY"))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--check-package-links", action="store_true")
    args = parser.parse_args()
    if args.check and args.check_package_links:
        parser.error("--check and --check-package-links are mutually exclusive")
    if not args.repository_slug:
        parser.error("--repository-slug is required outside GitHub Actions")
    repository = args.repository_root.resolve()
    works = catalog_works(repository, args.repository_slug)
    if args.check_package_links:
        mismatches = package_link_mismatches(repository, works)
        if mismatches:
            print("stale package links: " + "; ".join(mismatches), file=sys.stderr)
            return 1
        print("package links valid")
        return 0
    outputs = {repository / "catalog.yaml": render_yaml(works), repository / "CATALOG.md": render_markdown(works)}
    if args.check:
        stale = [str(path) for path, expected in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != expected]
        if stale:
            print("stale derived catalog: " + ", ".join(stale), file=sys.stderr)
            return 1
        print(f"catalog valid ({len(works)} projects)")
        return 0
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    print(f"updated catalog.yaml and CATALOG.md ({len(works)} projects)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
