#!/usr/bin/env python3
"""Regenerate the derived repository work catalog from released project.yaml files."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

TYPE_LABELS = {"tv": "TV", "movie": "电影", "ova": "OVA", "ona": "ONA", "special": "特别篇"}


def scalar(text: str, name: str, indent: int = 0) -> str | None:
    match = re.search(rf"(?m)^{' ' * indent}{re.escape(name)}:\s*(.*?)\s*$", text)
    if not match:
        return None
    value = match.group(1).strip()
    if value == "null":
        return None
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        value = value[1:-1]
    return value


def section(text: str, name: str, indent: int = 0) -> str:
    lines = text.splitlines()
    prefix = " " * indent + name + ":"
    start = next((index for index, line in enumerate(lines) if line == prefix), None)
    if start is None:
        return ""
    result = []
    for line in lines[start + 1 :]:
        if line.strip() and len(line) - len(line.lstrip(" ")) <= indent:
            break
        result.append(line)
    return "\n".join(result)


def released_works(repository: Path) -> list[dict[str, object]]:
    works = []
    for metadata_path in repository.glob("works/**/project.yaml"):
        current = metadata_path.parent / "subtitles" / "current"
        version = current / "VERSION"
        if not version.is_file() or not list(current.glob("*.ass")):
            continue
        text = metadata_path.read_text(encoding="utf-8-sig")
        identity = section(text, "identity")
        titles = section(identity, "titles", 2)
        languages = section(section(text, "languages"), "release", 2)
        item = {
            "id": scalar(text, "id"), "path": metadata_path.parent.relative_to(repository).as_posix(),
            "title": scalar(titles, "zh-Hans", 4), "type": scalar(text, "type"),
            "episode_count": int(scalar(text, "episode_count") or 0), "primary": scalar(languages, "primary", 4),
            "secondary": scalar(languages, "secondary", 4),
        }
        if not item["id"] or not item["title"] or item["type"] not in TYPE_LABELS:
            raise ValueError(f"invalid released project metadata: {metadata_path}")
        works.append(item)
    return sorted(works, key=lambda item: int(str(item["id"])[2:]))


def render_yaml(works: list[dict[str, object]]) -> str:
    lines = ["# Generated by $subtitle-hub scripts/sync_catalog.py; project.yaml remains authoritative.", "schema_version: 3", "", "works:"]
    for item in works:
        lines.extend([
            f"  - id: {item['id']}", f"    path: {item['path']}", f"    title: {json.dumps(item['title'], ensure_ascii=False)}",
            f"    type: {item['type']}", f"    episode_count: {item['episode_count']}",
            "    release_path: subtitles/current", "    version_file: subtitles/current/VERSION", "    package_directory: packages",
        ])
    return "\n".join(lines) + "\n"


def render_markdown(works: list[dict[str, object]]) -> str:
    lines = [
        "# 字幕目录", "", "<!-- Generated by $subtitle-hub scripts/sync_catalog.py; edit project.yaml instead. -->", "",
        "| ID | 作品 | 类型 | 集数 | 语言 / 格式 | 当前成品 |", "| --- | --- | --- | ---: | --- | --- |",
    ]
    for item in works:
        languages = str(item["primary"])
        if item["secondary"]:
            languages += f" + {item['secondary']}"
        lines.append(
            f"| {item['id']} | [{item['title']}]({item['path']}/README.md) | {TYPE_LABELS[str(item['type'])]} | "
            f"{item['episode_count']} | `{languages}` / ASS | [packages](packages) |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository-root", type=Path, default=Path(__file__).resolve().parents[4])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repository = args.repository_root.resolve()
    works = released_works(repository)
    outputs = {repository / "catalog.yaml": render_yaml(works), repository / "CATALOG.md": render_markdown(works)}
    if args.check:
        stale = [str(path) for path, expected in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != expected]
        if stale:
            print("stale derived catalog: " + ", ".join(stale), file=sys.stderr)
            return 1
        print(f"catalog valid ({len(works)} released works)")
        return 0
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    print(f"updated catalog.yaml and CATALOG.md ({len(works)} released works)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
